version: '3'
services:
  postgres:
    build:
      context: ./postgres/
    image: christopherfujino/postgres-dev:latest
    #image: postgres:12
    volumes:
      - ./postgres/local_data:/var/lib/postgresql/data
  rails:
    build:
      context: ./rails/
    image: christopherfujino/peas-budget-dev:latest
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - ./rails:/myapp
      - ./rails/vendor:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - postgres
